- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    state: absent
    autoremove: true
    purge: true
- name: Open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present
